return {
	PlaceObj('ModItemCode', {
		'name', "NoMaps_Autonomy",
		'CodeFileName', "Code/NoMaps_Autonomy.lua",
	}),
	PlaceObj('ModItemFolder', {
		'name', "NoMapsLoot",
		'comment', "Container inject packs for vanilla HotDiamonds without jazz-maps (JAZZ_AMMO_* / live weapons only)",
	}, {
		PlaceObj('ModItemLootDef', {
			Comment = "Common consumables for NoMaps container inject",
			group = "JAZZ_NoMaps",
			id = "JAZZ_NoMaps_Container_Common",
			loot = "all",
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 70,
				item = "Meds",
				stack_max = 4,
				stack_min = 1,
				weight = 10000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 40,
				item = "FragGrenade",
				stack_max = 2,
				stack_min = 1,
				weight = 8000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 35,
				item = "SmokeGrenade",
				stack_max = 2,
				stack_min = 1,
				weight = 7000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 25,
				item = "Lockpick",
				stack_max = 1,
				stack_min = 1,
				weight = 5000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 20,
				item = "Wirecutter",
				stack_max = 1,
				stack_min = 1,
				weight = 4000,
			}),
		}),
		PlaceObj('ModItemLootDef', {
			Comment = "JAZZ ammo for NoMaps container inject (no vanilla _* / TEST.png)",
			group = "JAZZ_NoMaps",
			id = "JAZZ_NoMaps_Container_Ammo",
			loot = "all",
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 50,
				item = "JAZZ_AMMO_9x19_FMJ",
				stack_max = 30,
				stack_min = 10,
				weight = 10000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 45,
				item = "JAZZ_AMMO_556_FMJ",
				stack_max = 30,
				stack_min = 10,
				weight = 9000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 40,
				item = "JAZZ_AMMO_762x51_FMJ",
				stack_max = 30,
				stack_min = 10,
				weight = 8000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 40,
				item = "JAZZ_AMMO_762x39_FMJ",
				stack_max = 30,
				stack_min = 10,
				weight = 8000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 35,
				item = "JAZZ_AMMO_12gauge_Buckshot",
				stack_max = 12,
				stack_min = 4,
				weight = 7000,
			}),
		}),
		PlaceObj('ModItemLootDef', {
			Comment = "Live JAZZ weapons for NoMaps inject (no MP5/AR15/M4Commando cut stubs)",
			group = "JAZZ_NoMaps",
			id = "JAZZ_NoMaps_Container_Weapon",
			loot = "all",
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 25,
				item = "AK47",
				weight = 10000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 20,
				item = "MP5A2",
				weight = 9000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 20,
				item = "UZI",
				weight = 8000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 15,
				item = "Galil",
				weight = 7000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 15,
				item = "FAMAS",
				weight = 7000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 20,
				item = "Glock18",
				weight = 8000,
			}),
		}),
	}),
}
