return {
	PlaceObj('ModItemCode', {
		'name', "NoMaps_Autonomy",
		'CodeFileName', "Code/NoMaps_Autonomy.lua",
	}),
	PlaceObj('ModItemFolder', {
		'name', "NoMapsLoot",
		'comment', "Tiered container inject packs by JAZZ_Legion_Tier major (COMPAT-004)",
	}, {
		-- T1: sparse; light ammo/common; rare light armor / SMG-pistol
		PlaceObj('ModItemLootDef', {
			Comment = "T1 common consumables",
			group = "JAZZ_NoMaps",
			id = "JAZZ_NoMaps_Container_Common_T1",
			loot = "all",
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 60,
				item = "Meds",
				stack_max = 3,
				stack_min = 1,
				weight = 10000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 20,
				item = "Lockpick",
				stack_max = 1,
				stack_min = 1,
				weight = 5000,
			}),
		}),
		PlaceObj('ModItemLootDef', {
			Comment = "T1 ammo (Poor/FMJ, small stacks)",
			group = "JAZZ_NoMaps",
			id = "JAZZ_NoMaps_Container_Ammo_T1",
			loot = "all",
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 55,
				item = "JAZZ_AMMO_9x19_Poor",
				stack_max = 18,
				stack_min = 6,
				weight = 10000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 40,
				item = "JAZZ_AMMO_9x19_FMJ",
				stack_max = 18,
				stack_min = 6,
				weight = 8000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 35,
				item = "JAZZ_AMMO_762x39_Poor",
				stack_max = 18,
				stack_min = 6,
				weight = 7000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 25,
				item = "JAZZ_AMMO_12gauge_Buckshot",
				stack_max = 8,
				stack_min = 2,
				weight = 5000,
			}),
		}),
		PlaceObj('ModItemLootDef', {
			Comment = "T1 weapons (pistol/SMG only)",
			group = "JAZZ_NoMaps",
			id = "JAZZ_NoMaps_Container_Weapon_T1",
			loot = "all",
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 40,
				item = "HiPower",
				weight = 10000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 25,
				item = "UZI",
				weight = 7000,
			}),
		}),
		PlaceObj('ModItemLootDef', {
			Comment = "T1 armor (light only)",
			group = "JAZZ_NoMaps",
			id = "JAZZ_NoMaps_Container_Armor_T1",
			loot = "all",
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 50,
				item = "JazzArmor_FlakM69",
				weight = 10000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 40,
				item = "JazzArmor_LeatherPants",
				weight = 8000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 35,
				item = "JazzArmor_M1Helm",
				weight = 7000,
			}),
		}),
		-- T2
		PlaceObj('ModItemLootDef', {
			Comment = "T2 common",
			group = "JAZZ_NoMaps",
			id = "JAZZ_NoMaps_Container_Common_T2",
			loot = "all",
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 65,
				item = "Meds",
				stack_max = 4,
				stack_min = 1,
				weight = 10000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 30,
				item = "FragGrenade",
				stack_max = 2,
				stack_min = 1,
				weight = 7000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 25,
				item = "SmokeGrenade",
				stack_max = 2,
				stack_min = 1,
				weight = 6000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 20,
				item = "Lockpick",
				stack_max = 1,
				stack_min = 1,
				weight = 4000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 15,
				item = "Wirecutter",
				stack_max = 1,
				stack_min = 1,
				weight = 3000,
			}),
		}),
		PlaceObj('ModItemLootDef', {
			Comment = "T2 ammo",
			group = "JAZZ_NoMaps",
			id = "JAZZ_NoMaps_Container_Ammo_T2",
			loot = "all",
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 50,
				item = "JAZZ_AMMO_9x19_FMJ",
				stack_max = 24,
				stack_min = 8,
				weight = 10000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 40,
				item = "JAZZ_AMMO_556_FMJ",
				stack_max = 24,
				stack_min = 8,
				weight = 8000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 40,
				item = "JAZZ_AMMO_762x39_FMJ",
				stack_max = 24,
				stack_min = 8,
				weight = 8000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 30,
				item = "JAZZ_AMMO_12gauge_Buckshot",
				stack_max = 10,
				stack_min = 4,
				weight = 6000,
			}),
		}),
		PlaceObj('ModItemLootDef', {
			Comment = "T2 weapons",
			group = "JAZZ_NoMaps",
			id = "JAZZ_NoMaps_Container_Weapon_T2",
			loot = "all",
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 30,
				item = "AK47",
				weight = 10000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 25,
				item = "MP5A2",
				weight = 9000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 20,
				item = "UZI",
				weight = 8000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 20,
				item = "Glock18",
				weight = 7000,
			}),
		}),
		PlaceObj('ModItemLootDef', {
			Comment = "T2 armor (mostly light, rare medium helm)",
			group = "JAZZ_NoMaps",
			id = "JAZZ_NoMaps_Container_Armor_T2",
			loot = "all",
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 45,
				item = "JazzArmor_FlakM69",
				weight = 10000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 35,
				item = "JazzArmor_FlakM1955",
				weight = 9000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 35,
				item = "JazzArmor_LeatherPants",
				weight = 7000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 30,
				item = "JazzArmor_M1Helm",
				weight = 7000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 15,
				item = "JazzArmor_PASGTHelm",
				weight = 4000,
			}),
		}),
		-- T3
		PlaceObj('ModItemLootDef', {
			Comment = "T3 common",
			group = "JAZZ_NoMaps",
			id = "JAZZ_NoMaps_Container_Common_T3",
			loot = "all",
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 70,
				item = "Meds",
				stack_max = 4,
				stack_min = 1,
				weight = 10000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 40,
				item = "FragGrenade",
				stack_max = 2,
				stack_min = 1,
				weight = 8000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 35,
				item = "SmokeGrenade",
				stack_max = 2,
				stack_min = 1,
				weight = 7000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 25,
				item = "Lockpick",
				stack_max = 1,
				stack_min = 1,
				weight = 5000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 20,
				item = "Wirecutter",
				stack_max = 1,
				stack_min = 1,
				weight = 4000,
			}),
		}),
		PlaceObj('ModItemLootDef', {
			Comment = "T3 ammo",
			group = "JAZZ_NoMaps",
			id = "JAZZ_NoMaps_Container_Ammo_T3",
			loot = "all",
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 50,
				item = "JAZZ_AMMO_9x19_FMJ",
				stack_max = 30,
				stack_min = 10,
				weight = 10000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 45,
				item = "JAZZ_AMMO_556_FMJ",
				stack_max = 30,
				stack_min = 10,
				weight = 9000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 40,
				item = "JAZZ_AMMO_762x51_FMJ",
				stack_max = 30,
				stack_min = 10,
				weight = 8000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 40,
				item = "JAZZ_AMMO_762x39_FMJ",
				stack_max = 30,
				stack_min = 10,
				weight = 8000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 35,
				item = "JAZZ_AMMO_12gauge_Buckshot",
				stack_max = 12,
				stack_min = 4,
				weight = 7000,
			}),
		}),
		PlaceObj('ModItemLootDef', {
			Comment = "T3 weapons",
			group = "JAZZ_NoMaps",
			id = "JAZZ_NoMaps_Container_Weapon_T3",
			loot = "all",
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 25,
				item = "AK47",
				weight = 10000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 20,
				item = "MP5A2",
				weight = 9000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 20,
				item = "UZI",
				weight = 8000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 15,
				item = "Galil",
				weight = 7000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 15,
				item = "FAMAS",
				weight = 7000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 20,
				item = "Glock18",
				weight = 8000,
			}),
		}),
		PlaceObj('ModItemLootDef', {
			Comment = "T3 armor",
			group = "JAZZ_NoMaps",
			id = "JAZZ_NoMaps_Container_Armor_T3",
			loot = "all",
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 45,
				item = "JazzArmor_FlakM69",
				weight = 10000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 35,
				item = "JazzArmor_FlakM1955",
				weight = 9000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 30,
				item = "JazzArmor_GuardianMedium",
				weight = 8000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 35,
				item = "JazzArmor_LeatherPants",
				weight = 7000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 25,
				item = "JazzArmor_GuardianLegs",
				weight = 6000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 35,
				item = "JazzArmor_M1Helm",
				weight = 7000,
			}),
			PlaceObj('LootEntryInventoryItem', {
				generate_chance = 25,
				item = "JazzArmor_PASGTHelm",
				weight = 6000,
			}),
		}),
	}),
}
