return PlaceObj('ModDef', {
	'title', "JAZZ Vanilla Maps",
	'description', "Optional JAZZ package for vanilla HotDiamonds maps (instead of jazz-maps): Legion AI, squad wiring, unit remap, and loot inject.\n\nInstall instead of jazz-maps:\n1. JAZZ Assets\n2. JAZZ Units\n3. JAZZ Vanilla Maps\n4. JAZZ\n(+ JA3_CommonLib)\n\nDisable this mod when using jazz-maps. If both are enabled, this package stays inactive.\n\nОпциональный пакет JAZZ для vanilla-карт HotDiamonds (вместо jazz-maps): Legion AI, wiring отрядов, подмена юнитов и лут.\nСтавить вместо maps. При включённом jazz-maps — no-op.",
	'last_changes', "v0.9.3: skip named Legion UnitData remap (Bastien / LegionRaider_Jose stays Bastien, not Marauder).\nv0.9.2: display title → JAZZ Vanilla Maps (id 7MsJ2Eq unchanged).\nv0.9: COMPAT-004 — force Major HQ A20; adopt InitialSquads as garrison; seed POI; vanilla Legion UnitData→JAZZ pools; container loot by JAZZ_Legion_Tier.\nv0.8: fix sparse gv_Squads gear refresh; missing-def log; Thugs affiliation; tier hook after bootstrap; expand remap.\nv0.7: Global AI playable — manpower 40, Tax/Recruiter on; clear ErnieIsland.Sectors; economy rev migrate.\nv0.6: remap Flak/Kevlar/HeavyArmor stubs → JazzArmor on gear refresh; armor loot pack for containers.\n- Packaging: expand .gitignore + metadata ignore_files for Steam upload",
	'id', "7MsJ2Eq",
	'author', "Kpoji4er",
	'version_major', 0,
	'version_minor', 9,
	'version', 4,
	'lua_revision', 233360,
	'saved_with_revision', 366685,
	'code', {
		"Code/NoMaps_Autonomy.lua",
	},
	'default_options', {},
	'ignore_files', {
		-- VCS / IDE / agent (tracked in git, not for Steam pack)
		"*.git/*",
		"*.svn/*",
		"*.github/*",
		"*.agents/*",
		"*.cursor/*",
		"*.tmp/*",
		"*codex_worktrees/*",
		-- Dev docs & tooling (in git, not runtime)
		"*docs/*",
		"*scripts/*",
		"*_localization/*",
		-- Intermediates / backups (also listed in .gitignore)
		"*__pycache__/*",
		"*_review/*",
		"*_raw/*",
		"*_neural/*",
		"*_wip/*",
		"*MercPortraits/References/*",
		"*MercPortraits/style-ja3-match/*",
		"*MercPortraits/newrules2/*",
		"*MercPortraits/wip-regen*/*",
		"*.psd",
		"*.psd/*",
		"*.bak",
		"*.bak_*",
		"*.pyc",
		"*.pyo",
		"*.zip",
		"*.md",
		"*.md/*",
		"*.ja3-root.local",
		"*.gitignore",
		"*.gitattributes",
		"*Thumbs.db",
		"*.DS_Store",
	},
	'dependencies', {
		PlaceObj('ModDependency', {
			'id', "e6L4ECj",
			'title', "JAZZ",
		}),
		PlaceObj('ModDependency', {
			'id', "Dv3mFVN",
			'title', "JAZZ Units",
		}),
		PlaceObj('ModDependency', {
			'id', "pDGDhr",
			'title', "JAZZ Assets",
		}),
		PlaceObj('ModDependency', {
			'id', "JA3_CommonLib",
			'title', "JA3_CommonLib",
			'version_major', 1,
			'version_minor', 11,
			'required', false,
		}),
	},
})
